final products = [
  {
    'id': 0,
    'title': 'Prime Choice Rice',
    'price': 468.05,
    'splitPrice': 93.61,
    'imageUrl': 'assets/images/prime_choice.png',
    'Brand': 'Prime Choice',
    'splitQuanttity': 5,
    'size': '5x5kg',
    'category': 'Rice & Spaghetti',
    'totalWeight': '25kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of rice containing 5 sacks of 5kg Prime Choice rice',
  },
  {
    'id': 1,
    'title': 'Lele Rice',
    'price': 468.05,
    'splitPrice': 116.16,
    'imageUrl': 'assets/images/lele_rice.png',
    'Brand': 'Lele',
    'splitQuanttity': 5,
    'size': '5x5kg',
    'category': 'Rice & Spaghetti',
    'totalWeight': '25kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of rice containing 5 sacks of 5kg Lele rice',
  },
  {
    'id': 2,
    'title': 'Lele Spaghetti',
    'price': 138.88,
    'splitPrice': 6.94,
    'imageUrl': 'assets/images/lele_spag.png',
    'Brand': 'Lele',
    'splitQuanttity': 20,
    'size': '20x450kg',
    'category': 'Rice & Spaghetti',
    'totalWeight': '9kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Lele spaghetti weighing 9 kilograms, which contains 20 packets.',
  },
  {
    'id': 3,
    'title': 'Rosalinda Spaghetti',
    'price': 127.68,
    'splitPrice': 6.38,
    'imageUrl': 'assets/images/rosalinda_spag.png',
    'Brand': 'Rosalinda',
    'splitQuanttity': 20,
    'size': '20x450g',
    'category': 'Rice & Spaghetti',
    'totalWeight': '9kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Rosalinda spaghetti weighing 450 grams, which includes 20 packets.',
  },
  {
    'id': 4,
    'title': 'Wesson Canola',
    'price': 330.40,
    'splitPrice': Null,
    'imageUrl': 'assets/images/wesson_oil.png',
    'Brand': 'Wesson',
    'splitQuanttity': Null,
    'size': '1x4.73L',
    'category': 'Cooking Oil',
    'totalWeight': '4.73L',
    'supplierMOQ': '1 Bottle',
    'details': '1 bottle of canola Oil by Wesson weighing 4.73 litres',
  },
  {
    'id': 5,
    'title': 'Lele Vegetable Oil',
    'price': 536.90,
    'splitPrice': Null,
    'imageUrl': 'assets/images/lele_oil.png',
    'Brand': 'Lele',
    'splitQuanttity': Null,
    'size': '1x25L',
    'category': 'Cooking Oil',
    'totalWeight': '25L',
    'supplierMOQ': 'Full Gallon (25L)',
    'details': '1 gallon of vegetable oil by Lele weighing 25 litres',
  },
  {
    'id': 6,
    'title': 'Frytol Oil',
    'price': 571.20,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Frytol_Oil.png',
    'Brand': 'Frytol',
    'splitQuanttity': Null,
    'size': '1x25L',
    'category': 'Cooking Oil',
    'totalWeight': '25L',
    'supplierMOQ': 'Full Gallon (25L)',
    'details': '1 gallon of cooking oil by frytol weighing 25 litres',
  },
  {
    'id': 7,
    'title': 'Chicken Breast (Brazil)',
    'price': 572.00,
    'splitPrice': 95.33,
    'imageUrl': 'assets/images/chicken_breast_brazil.png',
    'Brand': 'Unknown',
    'splitQuanttity': 6,
    'size': '6x2kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '12kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of chicken breast imported from brazil',
    
  },
  {
    'id': 8,
    'title': 'Chicken Wings A',
    'price': 385.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Chicken _wings_A.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of imported chicken wings A',
    
  },
  {
    'id': 9,
    'title': 'Chicken Wings B',
    'price': 330.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/chicken_wings_b.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of imported chicken wings B',
    
  },
  {
    'id': 10,
    'title': 'Chicken Thigh (Brazil)',
    'price': 297.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Chicken_thigh_Brazil.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of imported chicken thighs imported from brazil',
    
  },
  {
    'id': 11,
    'title': 'Chicken Drumsticks',
    'price': 352.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/chicken_drumsticks_brazil.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of imported chicken drumsticks',
    
  },
  {
    'id': 12,
    'title': 'Chicken Sausage (Lebon - Brazil)',
    'price': 280.00,
    'splitPrice': 11.67,
    'imageUrl': 'assets/images/chicken_sausage.png',
    'Brand': 'Sadia',
    'splitQuanttity': 24,
    'size': '24x340g',
    'category': 'Poultry (Imported)',
    'totalWeight': '8.16kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of 24 packets of chicken sausages',
    
  },
  {
    'id': 13,
    'title': 'Chicken Gizzard',
    'price': 286.00,
    'splitPrice': 28.60,
    'imageUrl': 'assets/images/chicken_gizzard.png',
    'Brand': 'Unknown',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of 10 packets of chicken gizard',
    
  },
  {
    'id': 14,
    'title': 'Turkey Wings',
    'price': 495.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/turkey_wings.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '10x1kg',
    'category': 'Poultry (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of Turkey wings',
    
  },
  {
    'id': 15,
    'title': 'White Fish Fillet Grade A',
    'price': 352.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/white_fish_fillet_grade_a.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '10x1kg',
    'category': 'Fish (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of grade A White Fish Fillet',
    
  },
  {
    'id': 16,
    'title': 'Grouper Fillet 300/500',
    'price': 352.00,
    'splitPrice': 99.00,
    'imageUrl': 'assets/images/Grouper_Fillet.png',
    'Brand': 'Unknown',
    'splitQuanttity': 6,
    'size': '1x6kg',
    'category': 'Fish (Imported)',
    'totalWeight': '6kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of Grouper Fillet (300/500)',
    
  },
  {
    'id': 17,
    'title': 'Red Fish (200/400G)',
    'price': 418.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/red_fish.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fish (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of Red Fish (200/400G)',
  },
  {
    'id': 18,
    'title': 'Mackrel 25+',
    'price': 275.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Mackrel_25.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fish (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of Mackrel (25+)',
    
  },
  {
    'id': 19,
    'title': 'Hake Fish',
    'price': 385.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/hake_fish.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fish (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': '1 box of hake fish',
    
  },
  {
    'id': 20,
    'title': 'Grouper Steak',
    'price': 112.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/grouper_steak.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x1kg',
    'category': 'Fish (Imported)',
    'totalWeight': '1kg',
    'supplierMOQ': '1kg',
    'details': '1kg of Grouper Steak',
    
  },
  {
    'id': 21,
    'title': 'Fresh Salmon (Portion/Steak)',
    'price': 303.75,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Fresh_salmon.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '1x1kg',
    'category': 'Fish (Imported)',
    'totalWeight': '1kg',
    'supplierMOQ': '1kg',
    'details': '1kg of Portion/Steak of Fresh Salmon',
    
  },
  {
    'id': 22,
    'title': 'Smoked Salmon',
    'price': 82.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/smoked_salmon.png',
    'Brand': 'Unknown',
    'splitQuanttity': Null,
    'size': '100g',
    'category': 'Fish (Imported)',
    'totalWeight': '100g',
    'supplierMOQ': '500g',
    'details': '100g of Smoked Salmon',
    
  },
  {
    'id': 23,
    'title': 'Tiger Prawns (8/12)',
    'price': 2100.00,
    'splitPrice': 210.00,
    'imageUrl': 'assets/images/Tiger_prawns_8_12.png',
    'Brand': 'None',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Sea Food (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': '1kg',
    'details': '10kg of Tiger Prawns (8/12)',
    
  },
  {
    'id': 24,
    'title': 'Tiger Prawns (10/20)',
    'price': 1900.00,
    'splitPrice': 190.00,
    'imageUrl': 'assets/images/Tiger_prawns__10_20.png',
    'Brand': 'None',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Sea Food (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': '1kg',
    'details': '10kg of Tiger Prawns (10/20)',
    
  },
  {
    'id': 25,
    'title': 'Peeled Prawns (10/15)',
    'price': 2100.00,
    'splitPrice': 105.00,
    'imageUrl': 'assets/images/peeled_prawns_10_15.png',
    'Brand': 'None',
    'splitQuanttity': 20,
    'size': '20x500g',
    'category': 'Sea Food (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': '500g',
    'details': '10kg of Tiger Prawns (8/12)',
    
  },
  {
    'id': 26,
    'title': 'Onion Rings',
    'price': 396.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/onion_rings.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '16x600g',
    'category': 'Vegetables (Imported)',
    'totalWeight': '9.6kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Onion Rings',
    
  },
  {
    'id': 27,
    'title': 'Green Peas',
    'price': 330.00,
    'splitPrice': 82.50,
    'imageUrl': 'assets/images/green_peas.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.5kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Green peas',
    
  },
  {
    'id': 28,
    'title': 'Broccoli',
    'price': 528.00,
    'splitPrice': 132.00,
    'imageUrl': 'assets/images/broccoli.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.5kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Broccoli',
    
  },
  {
    'id': 29,
    'title': 'Cauliflower',
    'price': 319.00,
    'splitPrice': 79.75,
    'imageUrl': 'assets/images/cauliflower.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.5kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Cauliflower',
  },
  {
    'id': 30,
    'title': 'Mixed Vegetables',
    'price': 319.00,
    'splitPrice': 79.75,
    'imageUrl': 'assets/images/mixed_vegetables.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.5kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Mixed Vegetables',
  },
  {
    'id': 31,
    'title': 'Edamame Soybeans',
    'price': 423.50,
    'splitPrice': 84.70,
    'imageUrl': 'assets/images/endamame_soybeans.png',
    'Brand': 'None',
    'splitQuanttity': 5,
    'size': '5x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '5kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Edamame Soybeans',
  },
  {
    'id': 32,
    'title': 'Sliced Mushrooms',
    'price': 368.50,
    'splitPrice': 36.85,
    'imageUrl': 'assets/images/sliced_mushrooms.png',
    'Brand': 'None',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of sliced mushrooms',
  },
  {
    'id': 33,
    'title': 'Sweet corn',
    'price': 495.00,
    'splitPrice': 49.50,
    'imageUrl': 'assets/images/sweet_corn.png',
    'Brand': 'None',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Sweet corn',
  },
  {
    'id': 34,
    'title': 'Blackberry',
    'price': 495.00,
    'splitPrice': 49.50,
    'imageUrl': 'assets/images/blackberry.png',
    'Brand': 'None',
    'splitQuanttity': 5,
    'size': '5x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '5kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Blackberry',
  },
  {
    'id': 35,
    'title': 'Raspberry',
    'price': 605.00,
    'splitPrice': 121.00,
    'imageUrl': 'assets/images/raspberry.png',
    'Brand': 'None',
    'splitQuanttity': 5,
    'size': '5x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '5kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Raspberry',
  },
  {
    'id': 36,
    'title': 'Strawberry',
    'price': 385.00,
    'splitPrice': 77.00,
    'imageUrl': 'assets/images/strawberry.png',
    'Brand': 'None',
    'splitQuanttity': 5,
    'size': '5x1kg',
    'category': 'Vegetables (Imported)',
    'totalWeight': '5kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Strawberry',
  },
  {
    'id': 37,
    'title': 'Beef bone-in',
    'price': 80.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Beef_bone-in.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Beef bone-in',
  },
  {
    'id': 38,
    'title': 'Beef Boneless',
    'price': 86.25,
    'splitPrice': Null,
    'imageUrl': 'assets/images/Beef_Boneless.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Beef Boneless',
  },
  {
    'id': 39,
    'title': 'Minced Beef',
    'price': 92.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/minced_beef.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Minced Beef',
  },
  {
    'id': 40,
    'title': 'Shredded beef',
    'price': 97.75,
    'splitPrice': Null,
    'imageUrl': 'assets/images/shredded_beef.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Shredded beef',
  },
  {
    'id': 41,
    'title': 'Goat Meat (Chevon)',
    'price': 92.00,
    'splitPrice': Null,
    'imageUrl': 'assets/images/goat.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Goat meat (Chevon)',
  },
  {
    'id': 42,
    'title': 'Pork bone-in',
    'price': 72.45,
    'splitPrice': Null,
    'imageUrl': 'assets/images/pork_bone-in.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Pork bone-in',
  },
  {
    'id': 43,
    'title': 'Pork chops',
    'price': 80.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/pork_chops.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Pork chops',
  },
  {
    'id': 44,
    'title': 'Pork boneless',
    'price': 86.25,
    'splitPrice': Null,
    'imageUrl': 'assets/images/pork_boneless.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Pork boneless',
  },
  {
    'id': 45,
    'title': 'Pork ribs',
    'price': 80.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/pork_ribs.png',
    'Brand': 'None',
    'splitQuanttity': Null,
    'size': '1x10kg',
    'category': 'Fresh Meat (Local)',
    'totalWeight': '10kg',
    'supplierMOQ': '10kg',
    'details': '10kg of Pork ribs',
  },
  {
    'id': 46,
    'title': 'Potato Chips (9x9MM)',
    'price': 316.25,
    'splitPrice': 79.06,
    'imageUrl': 'assets/images/fries.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.5kg',
    'category': 'Potato Chips',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of potato chips',
  },
  {
    'id': 47,
    'title': 'Mozzarella Cheese Block (Belgium)',
    'price': 880.00,
    'splitPrice': 220.00,
    'imageUrl': 'assets/images/mozzarella_cheese.png',
    'Brand': 'None',
    'splitQuanttity': 4,
    'size': '4x2.38kg',
    'category': 'Cheese & Cream',
    'totalWeight': '9.52kg',
    'supplierMOQ': '2.38kg',
    'details': 'A Block of belgian Mozzarella Cheese ',
  },
  {
    'id': 48,
    'title': 'Shredded Mozzarella Cheese (Poland)',
    'price': 766.50,
    'splitPrice': 95.81,
    'imageUrl': 'assets/images/Shredded_mozzerella_cheese.png',
    'Brand': 'None',
    'splitQuanttity': 8,
    'size': '8x1.5kg',
    'category': 'Cheese & Cream',
    'totalWeight': '12kg',
    'supplierMOQ': '1.5kg',
    'details': 'A packet of Shredded Mozzarella Cheese',
  },
  {
    'id': 49,
    'title': 'President Whipping cream',
    'price': 577.50,
    'splitPrice': 96.25,
    'imageUrl': 'assets/images/President_whipping_cream.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'Cheese & Cream',
    'totalWeight': '6L',
    'supplierMOQ': '1L',
    'details': 'A full carton of 6 packs of 1L President whipping cream',
  },
  {
    'id': 50,
    'title': 'President Cooking cream',
    'price': 525.00,
    'splitPrice': 87.50,
    'imageUrl': 'assets/images/president_cooking_cream.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'Cheese & Cream',
    'totalWeight': '6L',
    'supplierMOQ': '1L',
    'details': 'A full carton of 6 packs of 1L President cooking Cheese',
  },
  {
    'id': 51,
    'title': 'President Cream Cheese',
    'price': 735.00,
    'splitPrice': 122.50,
    'imageUrl': 'assets/images/President_cream_cheese.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'Cheese & Cream',
    'totalWeight': '6L',
    'supplierMOQ': '1L',
    'details': 'A full carton of 6 packs of 1L President Cream Cheese',
  },
  {
    'id': 52,
    'title': 'Galbani Parmesan',
    'price': 262.50,
    'splitPrice': Null,
    'imageUrl': 'assets/images/galbani_parmesan.png',
    'Brand': 'Galbani',
    'splitQuanttity': Null,
    'size': '1x1kg',
    'category': 'Cheese & Cream',
    'totalWeight': '1kg',
    'details': '1kg of Galbani parmesan cheese',
  },
  {
    'id': 53,
    'title': 'President Salted Butter',
    'price': 1875.00,
    'splitPrice': 46.88,
    'imageUrl': 'assets/images/president_salted_butter.png',
    'Brand': 'President',
    'splitQuanttity': 40,
    'size': '40x200kg',
    'category': 'Butter',
    'totalWeight': '8kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of President Salted Butter',
  },
  {
    'id': 54,
    'title': 'President Unsalted Butter',
    'price': 1875.00,
    'splitPrice': 46.88,
    'imageUrl': 'assets/images/president_unsalted_butter.png',
    'Brand': 'President',
    'splitQuanttity': 40,
    'size': '40x200kg',
    'category': 'Butter',
    'totalWeight': '8kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of President Unsalted Butter',
  },
  {
    'id': 55,
    'title': 'Bridel Unsalted Butter',
    'price': 1750.00,
    'splitPrice': 43.75,
    'imageUrl': 'assets/images/bridel_unsalted_butter.png',
    'Brand': 'Bridel',
    'splitQuanttity': 40,
    'size': '40x200kg',
    'category': 'Butter',
    'totalWeight': '8kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Bridel Unsalted Butter',
  },
  {
    'id': 56,
    'title': 'Ambassador Unsalted Butter',
    'price': 937.50,
    'splitPrice': 23.44,
    'imageUrl': 'assets/images/ambassador_unsalted_butter.png',
    'Brand': 'Ambassador',
    'splitQuanttity': 40,
    'size': '40x200kg',
    'category': 'Butter',
    'totalWeight': '8kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Ambassador Unsalted Butter',
  },
  {
    'id': 57,
    'title': 'Ambassador Salted Butter',
    'price': 937.50,
    'splitPrice': 23.44,
    'imageUrl': 'assets/images/ambassador_salted_butter.png',
    'Brand': 'Ambassador',
    'splitQuanttity': 40,
    'size': '40x200kg',
    'category': 'Butter',
    'totalWeight': '8kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Ambassador Salted Butter',
  },
  {
    'id': 58,
    'title': 'President Whole Milk 3.5%',
    'price': 150.00,
    'splitPrice': 25.00,
    'imageUrl': 'assets/images/president_whole_milk__3.5.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'UHT Milk/Juice',
    'totalWeight': '6L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 6 packs of 1L President Whole Milk 3.5%',
  },
  {
    'id': 59,
    'title': 'President Semi Skimmed Milk 1.5%',
    'price': 150.00,
    'splitPrice': 25.00,
    'imageUrl': 'assets/images/president_semi_skimmed_milk_1.5.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'UHT Milk/Juice',
    'totalWeight': '6L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 6 packs of 1L President Semi Skimmed Milk 1.5%',
  },
  {
    'id': 60,
    'title': 'President Skimmed Milk <0.3%',
    'price': 150.00,
    'splitPrice': 25.00,
    'imageUrl': 'assets/images/president_skimmed_milk.png',
    'Brand': 'President',
    'splitQuanttity': 6,
    'size': '6x1L',
    'category': 'UHT Milk/Juice',
    'totalWeight': '6L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 6 packs of 1L President Semi Skimmed Milk 1.5%',
  },
  {
    'id': 61,
    'title': 'Peak UHT Low Fat',
    'price': 324.00,
    'splitPrice': 27.00,
    'imageUrl': 'assets/images/Peak_UHT_Low_Fat.png',
    'Brand': 'Peak',
    'splitQuanttity': 12,
    'size': '12x1L',
    'category': 'UHT Milk/Juice',
    'totalWeight': '12L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Peak UHT Low Fat',
  },
  {
    'id': 62,
    'title': 'Good Morning Oats',
    'price': 276.00,
    'splitPrice': 23.00,
    'imageUrl': 'assets/images/good_morning_oats.png',
    'Brand': 'Good Morning',
    'splitQuanttity': 12,
    'size': '12x500g',
    'category': 'Pantry Goods',
    'totalWeight': '6kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 12 boxes of Good Morning oats',
  },
  {
    'id': 63,
    'title': 'Good Morning Cornflakes',
    'price': 504.00,
    'splitPrice': 42.00,
    'imageUrl': 'assets/images/Good_morning_cornflakes.png',
    'Brand': 'Good Morning',
    'splitQuanttity': 12,
    'size': '12x375g',
    'category': 'Pantry Goods',
    'totalWeight': '4.5kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 12 boxes of Good Morning Cornflakes',
  },
  {
    'id': 64,
    'title': 'Loacker Sandwich Wafer (Choc/Vanilla/Hazel)',
    'price': 127.68,
    'splitPrice': 5.11,
    'imageUrl': 'assets/images/Loacker_sandwich_wafer.png',
    'Brand': 'Loacker',
    'splitQuanttity': 25,
    'size': '25x25g',
    'category': 'Pantry Goods',
    'totalWeight': '50g',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Choc/Vanilla/Hazel Loacker Sandwich Wafer',
  },
  {
    'id': 65,
    'title': 'Lele White Sugar',
    'price': 199.10,
    'splitPrice': 19.91,
    'imageUrl': 'assets/images/lele_white_sugar.png',
    'Brand': 'Lele',
    'splitQuanttity': 10,
    'size': '10x1kg',
    'category': 'Pantry Goods',
    'totalWeight': '10kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 10 packets of Lele White Sugar',
  },
  {
    'id': 66,
    'title': 'Lele Salt',
    'price': 211.68,
    'splitPrice': 4.23,
    'imageUrl': 'assets/images/lele_salt.png',
    'Brand': 'Lele',
    'splitQuanttity': 50,
    'size': '50x500g',
    'category': 'Pantry Goods',
    'totalWeight': '25kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 5 packets of Lele Salt',
  },
  {
    'id': 67,
    'title': 'Geisha Mackerel',
    'price': 408.25,
    'splitPrice': 8.17,
    'imageUrl': 'assets/images/geisha_markerel.png',
    'Brand': 'Geisha',
    'splitQuanttity': 50,
    'size': '50x155g',
    'category': 'Pantry Goods',
    'totalWeight': '7.75kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Geisha mackerel',
  },
  {
    'id': 68,
    'title': 'Lele Tuna Chunks',
    'price': 384.10,
    'splitPrice': 16.00,
    'imageUrl': 'assets/images/Lele_tuna_chunks.png',
    'Brand': 'Lele',
    'splitQuanttity': 24,
    'size': '24x160g',
    'category': 'Pantry Goods',
    'totalWeight': '3.84kg',
    'supplierMOQ': 'Pantry Goods',
    'details': 'A full carton of Lele Tuna Chunks',
  },
  {
    'id': 69,
    'title': 'Lele Tuna Slices',
    'price': 432.40,
    'splitPrice': 18.02,
    'imageUrl': 'assets/images/Lele_tuna_slices.png',
    'Brand': 'Lele',
    'splitQuanttity': 24,
    'size': '24x125g',
    'category': 'Pantry Goods',
    'totalWeight': '3kg',
    'supplierMOQ': 'Pantry Goods',
    'details': 'A full carton of Lele Tuna Slices',
  },
  {
    'id': 70,
    'title': 'Titus Sardine',
    'price': 467.50,
    'splitPrice': 9.35,
    'imageUrl': 'assets/images/Titus_sardine.png',
    'Brand': 'Titus',
    'splitQuanttity': 50,
    'size': '50x125g',
    'category': 'Pantry Goods',
    'totalWeight': '6.25kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Titus Sardine',
  },
  {
    'id': 71,
    'title': 'Princess Sardine in Oil',
    'price': 420.20,
    'splitPrice': 8.40,
    'imageUrl': 'assets/images/Princess_sardine.png',
    'Brand': 'Princess Sardine',
    'splitQuanttity': 50,
    'size': '50x125g',
    'category': 'Pantry Goods',
    'totalWeight': '6.25kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Princess Sardine',
  },
  {
    'id': 72,
    'title': 'Heinz Tomato Ketchup',
    'price': 387.52,
    'splitPrice': 38.75,
    'imageUrl': 'assets/images/Heinz_tomato_ketchup.png',
    'Brand': 'Heinz',
    'splitQuanttity': 10,
    'size': '10x570g',
    'category': 'Pantry Goods',
    'totalWeight': '5.7kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 10 bottles of Heinz Tomato Ketchup',
  },
  {
    'id': 73,
    'title': 'Heinz Canned Corned Beef',
    'price': 849.45,
    'splitPrice': 35.39,
    'imageUrl': 'assets/images/heinz_canned_cornered_beef.png',
    'Brand': 'Heinz',
    'splitQuanttity': 24,
    'size': '24x340g',
    'category': 'Pantry Goods',
    'totalWeight': '8.16kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 24 cans of Heinz Canned Corned Beef',
  },
  {
    'id': 74,
    'title': 'Lele Corned Beef',
    'price': 404.25,
    'splitPrice': 33.69,
    'imageUrl': 'assets/images/Lele_corned_beef.png',
    'Brand': 'Lele',
    'splitQuanttity': 12,
    'size': '12x340g',
    'category': 'Pantry Goods',
    'totalWeight': '4.08kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Lele Corned Beef',
  },
  {
    'id': 75,
    'title': 'Tasty Tom Tomato Mix',
    'price': 273.35,
    'splitPrice': 11.39,
    'imageUrl': 'assets/images/tasty_tom_tomato_mix.png',
    'Brand': 'Tasty Tom',
    'splitQuanttity': 24,
    'size': '24x400g',
    'category': 'Pantry Goods',
    'totalWeight': '9.6kg',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Tasty Tom Tomato Mix',
  },
  {
    'id': 76,
    'title': 'Crystal Clear Liquid Soap (Lemon Flavour)',
    'price': 202.00,
    'splitPrice': 50.50,
    'imageUrl': 'assets/images/soap.png',
    'Brand': 'Crystal Clear',
    'splitQuanttity': 4,
    'size': '4x5L',
    'category': 'Household Items',
    'totalWeight': '20L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of Crystal Clear Liquid Soap',
  },
  {
    'id': 77,
    'title': 'Powerzone Thick Bleach (12x950ml)',
    'price': 168.00,
    'splitPrice': 14.00,
    'imageUrl': 'assets/images/powerzone_thick_bleach.png',
    'Brand': 'Powerzone',
    'splitQuanttity': 12,
    'size': '12x950mL',
    'category': 'Household Items',
    'totalWeight': '11.4L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 12 bottles of Powerzone Thick Bleach',
  },
  {
    'id': 78,
    'title': 'Powerzone Thick Bleach (20x950ml)',
    'price': 280.00,
    'splitPrice': 14.00,
    'imageUrl': 'assets/images/powerzone_thick_bleach.png',
    'Brand': 'Powerzone',
    'splitQuanttity': 20,
    'size': '20x950ml',
    'category': 'Household Items',
    'totalWeight': '19L',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 20 bottles of Powerzone Thick Bleach',
  },
  {
    'id': 79,
    'title': 'Fon Tissue Toilet Paper (1x48)',
    'price': 158.40,
    'splitPrice': 3.30,
    'imageUrl': 'assets/images/Fontissue_toilet_paper_7x10.png',
    'Brand': 'Fon Tissue',
    'splitQuanttity': 48,
    'size': '1x48pcs',
    'category': 'Household Items',
    'totalWeight': '48',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 48 pieces of Fon Tissue Toilet Paper',
  },
  {
    'id': 80,
    'title': 'Fon Tissue Toilet Paper (7x10)',
    'price': 218.40,
    'splitPrice': 3.12,
    'imageUrl': 'assets/images/Fontissue_toilet_paper_7x10.png',
    'Brand': 'Fon Tissue',
    'splitQuanttity': 70,
    'size': '7x10pcs',
    'category': 'Household Items',
    'totalWeight': '70pcs',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 7 packs of Fon Tissue Toilet Paper (10 per pack)',
  },
  {
    'id': 81,
    'title': 'Adepa multipurpose kitchen roll (2x8)',
    'price': 126.00,
    'splitPrice': 7.88,
    'imageUrl': 'assets/images/Adepa_multipurpose_kitchen_roll.png',
    'Brand': 'Adepa',
    'splitQuanttity': 16,
    'size': '2x8pcs',
    'category': 'Household Items',
    'totalWeight': '16pcs',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 2 packs of Adepa multipurpose kitchen roll (8 per pack)',
  },
  {
    'id': 82,
    'title': 'Adepa multipurpose kitchen roll (4x6)',
    'price': 180.00,
    'splitPrice': 7.50,
    'imageUrl': 'assets/images/Adepa_multipurpose_kitchen_roll.png',
    'Brand': 'Adepa',
    'splitQuanttity': 24,
    'size': '4x6pcs',
    'category': 'Household Items',
    'totalWeight': '24pcs',
    'supplierMOQ': 'Full Carton',
    'details': 'A full carton of 4 packs of Adepa multipurpose kitchen roll (6 per pack)',
  },
];
